version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  sso-server:
    build: ./sso_server
    ports:
      - "3010:3010"
    env_file:
      - .env
    depends_on:
      - redis

  consumer-app:
    build: ./consumer_app
    ports:
      - "3020:3020"
    env_file:
      - .env
    depends_on:
      - sso-server